### ISSUE TITLE
`pip check` isn't happy with latest release (3.1.0)

### ISSUE THREAD

**Issue by xylar** [conda-forge/filelock-feedstock#18]
In builds with the latest `filelock`, the version number in the metadata is 0.0.0.  This is causing issues with `pip check`.

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=383996&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=8961
```
virtualenv 20.4.7 has requirement filelock<4,>=3.0.0, but you have filelock 0.0.0.
```

I've seen this recently with another feedstock:
https://github.com/conda-forge/libcst-feedstock/issues/23
fixed in
https://github.com/conda-forge/libcst-feedstock/pull/24

I'll see if a similar fix will work here.  PR to come in a bit...

**Comment by nicoddemus** [comment]
Hi @xylar,

I think this might have been resolved already in more recent `setuptools-scm` releases so the workaround of setting the environment variable might not be necessary (however I'm not 100% sure so testing is needed).

**Comment by xylar** [comment]
I can try the same without the environment variable.  But I don't know where else the version number would come from in this case.  Upstream, they just don't seem to be setting the version number at all.
https://github.com/tox-dev/py-filelock/blob/3.1.0/setup.py#L3
https://github.com/tox-dev/py-filelock/blob/3.1.0/setup.cfg

**Comment by xylar** [comment]
@nicoddemus, you are right.  Just including `setuptools_scm` as a dependency seems to do it.
